### PR TITLE
Finished tests for all scripts

### PR DESCRIPTION
**Pull request by vedtopkar**
1. Wrote passing tests for `umitag.py` and `consolidate.py`. 
2. Added all test data and organized it neatly into `test/data`

### CODE REVIEW

**Comment by martinaryee** [comment]
test_umitag.py fails for me - could you take a look?

```
(venv-2.7.6)[ma695@rgs13 test]$ python test_umitag.py 
F
======================================================================
FAIL: testUMITagTestCase (__main__.TestUMITag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_umitag.py", line 45, in testUMITagTestCase
    self.assertTrue(utils.checkFolderEquality(TEST_OUTPUT_PATH, CORRECT_UMITAGGED_OUTPUT_FOLDER))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 1.498s

FAILED (failures=1)
(venv-2.7.6)[ma695@rgs13 test]$ 
(venv-2.7.6)[ma695@rgs13 test]$ git log | head
commit d680813735f100e30120d8e60caf28973f9c294c
Merge: 787138a aa39160
Author: Martin Aryee <martin.aryee@gmail.com>
Date:   Mon Sep 14 12:37:02 2015 -0400

    Merge pull request #7 from aryeelab/preliminary-tests

    Finished tests for all scripts

commit aa391607eb41bfc1ffc1c13d50c5570b9096e3ac
```

**Comment by vedtopkar** [comment]
Hmmm, are you on python2.7? I just cloned a clean version of the repo and all tests are passing for me :disappointed_relieved:

**Comment by vedtopkar** [comment]
Bump!

**Comment by martinaryee** [comment]
It worked for me in a clean environment. This inspired me to set up [Travis](https://travis-ci.org). We may have to refactor the tests somewhat and then add a .travis.yml to the repo to get automatic testing on push. http://docs.travis-ci.com/user/for-beginners/

**Comment by vedtopkar** [comment]
Found the error: to test for a script being correct the test checks for folder content equality. This fails if we've opened the folder in Finder, since that forces OSX to create a `.DS_Store` file, which gets in the way. Fixing now.

**Pull request merged**
