### PR TITLE
modified files and folder for external inependent use

### PR DESCRIPTION
**Pull request by vedtopkar**
Two main changes:
1. Added `__init__.py` so that the folder can be imported as a module from an external python script
2. Rearranged and rewrote small parts of the `demultiplex.py` and `consolidate.py` files so that they can be imported and used modularly from external python scripts.

### CODE REVIEW

**Comment by vedtopkar** [comment]
Changed target branch to `dev` as requested!

**Comment by martinaryee** [comment]
Could you check if the dev branch now behaves as you expect? If so, I'll go ahead and merge into master and tag this version with v1.1

**Comment by vedtopkar** [comment]
Sure thing. I'm currently writing some tests so that this can be done in an automated fashion.

One question I have is what the `min_read` threshold should be for the tests, since we are only using a small subset of the undemultiplexed data for testing. Perhaps @shengdar can shed some light on this too.

**Comment by martinaryee** [comment]
I have a bare minimum usage example here: https://github.com/aryeelab/umi/wiki
It uses the example data in the "example" folder and sets min_reads to 1000.

**Comment by vedtopkar** [comment]
Oops, I should have RTFD. Thanks!

**Comment by shengdar** [comment]
Haha, sounds like you guys have it under control. :-)

S

**Comment by vedtopkar** [comment]
Just wrote the last tests and put in a PR. Once you merge into `dev`, go ahead and try it out. I think it's ready to be merged into `master` and tagged v1.1 :+1:

**Pull request merged**
